version: '2'
services:
    mssjapp-app:
        image: mssjapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssjapp-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mssjapp-mssql:
        extends:
            file: mssql.yml
            service: mssjapp-mssql
